[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
eth = "${RPC_1}"
goerli = "${RPC_5}"
polygon = "${RPC_137}"
op = "${RPC_10}"
arb = "${RPC_42161}"

[etherscan]
eth = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_137}" }
op = { key = "${ETHERSCAN_10}" }
arb = { key = "${ETHERSCAN_42161}" }
