[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["TelepathyOracle","TelepathyOracleFulfiller","NFTAirdrop","ENSQueryExample"]

[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
eth = "${MAINNET_RPC_URL}"
